[mypy]
exclude = (?x)(
    build
    | ^src/tests
    | ^src/maltego/template_dir/transforms/.*.py$
    | ^src/maltego/template_dir/project.py$
  )
disable_error_code = name-shadows-library

mypy_path = src

[mypy-snapshottest.*]
ignore_missing_imports = True

[mypy-maltego.entities.*]
ignore_missing_imports = True
