# Copyright (c) Maltego Technologies GmbH.
import typing
from typing import Any
import pytest
import httpx
from tests.conftest import NAMESPACE, PREFIX, UA_4_10_0, UA_9_9_9, GRAPH_BROWSER_3_0_0

pytestmark = pytest.mark.contract


def _strip_blobs(data: Any) -> Any:
    """Remove unstable generated values before snapshot comparison.

    PNG bytes are generated by Pillow and differ across Python/Pillow versions,
    making exact blob comparison unreliable in CI environments.
    """
    if isinstance(data, dict):
        return {
            k: _strip_blobs("<test-runtime-public-key>" if k == "accessTokenPublicKey" else v)
            for k, v in data.items()
            if k != 'blob'
        }
    if isinstance(data, list):
        return [_strip_blobs(item) for item in data]
    return data


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "route",
    [
        "/hub_item",
        "/assets",
        "/assets/entities",
        "/assets/icons",
        "/assets/machines",
        "/assets/sets",
        "/assets/oauthservice",
        "/transforms",
        "/.well-known/supported_capabilities",
    ],
)
async def test_prefixed_latest_discovery_routes_are_unversioned(
    async_client_mock_server: httpx.AsyncClient,
    route: str,
) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}{route}")
    assert response.status_code == 200


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "route",
    [
        "/hub_item",
        "/assets",
        "/assets/entities",
        "/assets/icons",
        "/assets/machines",
        "/assets/sets",
        "/assets/oauthservice",
        "/transforms",
        "/.well-known/supported_capabilities",
    ],
)
async def test_legacy_v3_discovery_routes_remain_available(
    async_client_mock_server: httpx.AsyncClient,
    route: str,
) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/api/v3{route}")
    assert response.status_code == 200


@pytest.mark.asyncio
async def test_supported_capabilities_response_shape_is_stable(
    async_client_mock_server: httpx.AsyncClient,
) -> None:
    response = await async_client_mock_server.get(
        f"{PREFIX}/.well-known/supported_capabilities"
    )

    assert response.status_code == 200
    assert response.json() == {
        "protocol": "3.2",
        "supported_capabilities": [
            {
                "name": "inputConstraints",
                "description": "Structured input-constraint transforms",
            },
            {
                "name": "compositeEntities",
                "description": "Full entity-typed structures",
            },
            {
                "name": "promptBase",
                "description": "Enable using prompts in transforms",
            },
            {
                "name": "choiceControlType",
                "description": "Specify control types in prompts",
            },
            {
                "name": "multiChoiceControls",
                "description": "Multiple controls per prompt",
            },
            {
                "name": "flattenedCompositeEntities",
                "description": "Flattened composite entities",
            },
            {
                "name": "inputConstraintsUnknownSafe",
                "description": "Client tolerates unknown input constraint types",
            },
        ],
    }


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_hub_item(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/hub_item")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_hub_item_example(async_client_example_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_example_server.get("api/v3/hub_item")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets")
    assert response.status_code == 200
    assert response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(response.json())
    response_dict = response.json()
    assert response_dict


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_example_server_assets(
    async_client_example_server: httpx.AsyncClient,
    snapshot: typing.Any
) -> None:

    asset_response = await async_client_example_server.get('/api/v3/assets')
    assert asset_response.status_code == 200
    assert asset_response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(asset_response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_entities(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets/entities")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_entities_example(async_client_example_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_example_server.get("/api/v3/assets/entities")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_icons(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets/icons")
    assert response.status_code == 200
    assert snapshot == _strip_blobs(response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_icons_example(async_client_example_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_example_server.get("api/v3/assets/icons")
    assert response.status_code == 200
    assert snapshot == _strip_blobs(response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_machines(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets/machines")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_machines_example(
    async_client_example_server: httpx.AsyncClient,
    snapshot: typing.Any
) -> None:
    response = await async_client_example_server.get("api/v3/assets/machines")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_sets(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets/sets")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_sets_example(async_client_example_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_example_server.get("api/v3/assets/sets")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_oauthservice(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/assets/oauthservice")
    assert response.status_code == 200
    assert response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_assets_oauthservice_example(
    async_client_example_server: httpx.AsyncClient,
    snapshot: typing.Any
) -> None:
    response = await async_client_example_server.get("api/v3/assets/oauthservice")
    assert response.status_code == 200
    assert response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_example_server_transforms(
    async_client_example_server: httpx.AsyncClient,
    snapshot: typing.Any
) -> None:
    transform_response = await async_client_example_server.get('/api/v3/transforms')
    assert transform_response.status_code == 200
    assert transform_response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(transform_response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_transforms(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/transforms")
    assert response.status_code == 200
    assert response.headers["maltego-transform-supported-oauth-formats"] == "jwe"
    assert snapshot == _strip_blobs(response.json())


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_transform_example(async_client_example_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_example_server.get(f"api/v3/transforms/{PREFIX}.{NAMESPACE}.transform")
    assert response.status_code == 200
    assert snapshot == response.json()


@pytest.mark.asyncio
@pytest.mark.snapshot
async def test_get_transform(async_client_mock_server: httpx.AsyncClient, snapshot: typing.Any) -> None:
    response = await async_client_mock_server.get(f"{PREFIX}/transforms/{NAMESPACE}.Test")
    assert response.status_code == 200
    assert snapshot == response.json()


# --- Entity Config Overrides Tests ---

@pytest.mark.asyncio
async def test_desktop_client_gets_override_allowed_root(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """Desktop client should get allowed_root=True for configured entities."""
    # Request with desktop user agent
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=UA_4_10_0
    )
    assert response.status_code == 200

    entities = response.json()
    # Find the nonRootEntity which is configured to have allowed_root=True for desktop
    non_root = next((e for e in entities if e["id"] == "maltego.nonRootEntity"), None)
    assert non_root is not None, "maltego.nonRootEntity should be in response"
    assert non_root["allowedRoot"] is True, "Desktop should get allowed_root=True override"


@pytest.mark.asyncio
async def test_web_client_gets_default_allowed_root(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """Web client should get default allowed_root=False for entities not in override."""
    # Request with web client headers
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=GRAPH_BROWSER_3_0_0
    )
    assert response.status_code == 200

    entities = response.json()
    # Find the nonRootEntity - web client should get default allowed_root=False
    non_root = next((e for e in entities if e["id"] == "maltego.nonRootEntity"), None)
    assert non_root is not None, "maltego.nonRootEntity should be in response"
    assert non_root["allowedRoot"] is False, "Web should get default allowed_root=False"


@pytest.mark.asyncio
async def test_desktop_old_version_excludes_coalesce_entities(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """Desktop client should not receive atomic entities with coalesce (unless overridden)."""
    # Request with older desktop user agent (4.10.0)
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=UA_4_10_0
    )
    assert response.status_code == 200

    entities = response.json()
    entity_ids = [e["id"] for e in entities]

    # AtomicCoalesceTestEntity has NO override, so it should be excluded for old desktop
    assert "maltego.AtomicCoalesceTestEntity" not in entity_ids, \
        "Old desktop client should not receive atomic coalesce entities without override"


@pytest.mark.asyncio
async def test_layer1_override_removes_coalesce_layer2_allows(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """
    Test Layer 1 + Layer 2 interaction:
    CoalescingDisplayPropertyEntity originally has $coalesce() in field default_value,
    but the override changes it to "$property(name)" (no coalesce).
    Layer 2 should NOT skip it because after override, it no longer has coalesce.
    """
    # Request with older desktop user agent (4.10.0)
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=UA_4_10_0
    )
    assert response.status_code == 200

    entities = response.json()

    # Find CoalescingDisplayPropertyEntity - should be included because override removed coalesce
    entity = next(
        (e for e in entities if e["id"] == "maltego.CoalescingDisplayPropertyEntity"),
        None
    )
    assert entity is not None, \
        "CoalescingDisplayPropertyEntity should be included because override removed coalesce"

    # Verify the field's default_value was changed from coalesce to simple "$property(name)"
    fields = entity.get("properties", {}).get("fields", [])
    display_field = next((f for f in fields if f.get("name") == "display_property"), None)
    assert display_field is not None, "display_property field should exist"
    assert display_field.get("defaultValue") == "$property(name)", \
        "Override should have changed field default_value from coalesce"


@pytest.mark.asyncio
async def test_desktop_new_version_includes_coalesce_entities(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """Desktop client >= 9.9.9 should receive entities with original coalesce in field."""
    # Request with new desktop user agent (9.9.9 - COALESCE_MIN_DESKTOP)
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=UA_9_9_9
    )
    assert response.status_code == 200

    entities = response.json()

    # Find AtomicCoalesceTestEntity - should be included with ORIGINAL coalesce (no override)
    atomic_entity = next(
        (e for e in entities if e["id"] == "maltego.AtomicCoalesceTestEntity"),
        None
    )
    assert atomic_entity is not None, \
        "New desktop client should receive atomic coalesce entities"
    # AtomicCoalesceTestEntity has no override, so new desktop gets original coalesce
    fields = atomic_entity.get("properties", {}).get("fields", [])
    display_field = next((f for f in fields if f.get("name") == "display_property"), None)
    assert display_field is not None, "display_property field should exist"
    assert "$coalesce(" in str(display_field.get("defaultValue", "")), \
        "New desktop should receive original coalesce (no override configured)"


@pytest.mark.asyncio
async def test_web_client_includes_coalesce_entities(
    async_client_example_server: httpx.AsyncClient
) -> None:
    """Web client should receive entities with original coalesce in field default_value."""
    # Request with web client headers (include compositeEntities capability)
    headers = {**GRAPH_BROWSER_3_0_0, "maltego-client-capabilities": "compositeEntities"}
    response = await async_client_example_server.get(
        "/api/v3/assets/entities",
        headers=headers
    )
    assert response.status_code == 200

    entities = response.json()

    # Find AtomicCoalesceTestEntity - web client should get ORIGINAL coalesce in field
    atomic_entity = next(
        (e for e in entities if e["id"] == "maltego.AtomicCoalesceTestEntity"),
        None
    )
    assert atomic_entity is not None, \
        "Web client should receive atomic coalesce entities"
    # Web client gets original coalesce (no override for web)
    fields = atomic_entity.get("properties", {}).get("fields", [])
    display_field = next((f for f in fields if f.get("name") == "display_property"), None)
    assert display_field is not None, "display_property field should exist"
    assert "$coalesce(" in str(display_field.get("defaultValue", "")), \
        "Web client should receive original coalesce in field default_value"

    # Find CompositeCoalesceTestEntity - web client should get original coalesce in field
    composite_entity = next(
        (e for e in entities if e["id"] == "maltego.CompositeCoalesceTestEntity"),
        None
    )
    assert composite_entity is not None, \
        "Web client should receive composite coalesce entities"
    composite_fields = composite_entity.get("properties", {}).get("fields", [])
    composite_display_field = next((f for f in composite_fields if f.get("name") == "display_property"), None)
    assert composite_display_field is not None, "display_property field should exist"
    assert "$coalesce(" in str(composite_display_field.get("defaultValue", "")), \
        "Web client should receive original coalesce in field default_value for composite"
