# Copyright (c) Maltego Technologies GmbH.
"""Pins the wire aliases generated by the SDK-owned protocol ``APIModel``."""
from types import SimpleNamespace

import pytest

from maltego.protocol.v3.discovery.auth import V3OAuthServiceDefinition
from maltego.protocol.v3.discovery.seed import V3SeedResponse
from maltego.protocol.v3.discovery.status import V3StatusResponse
from maltego.protocol.v3.discovery.transform import TransformDiscoveryIO
from maltego.protocol.v3.execution.transform_run import TransformRunRequest, TransformSetting

pytestmark = pytest.mark.unit


@pytest.mark.parametrize(
    ("model", "field", "alias"),
    [
        (V3OAuthServiceDefinition, "access_token_endpoint", "accessTokenEndpoint"),
        (TransformDiscoveryIO, "type_ids", "typeIds"),
        (TransformDiscoveryIO, "type", "type"),
        # Digits: title() capitalizes the letter after a digit and the underscore
        # before a digit is dropped.
        (V3SeedResponse, "maltego_v3_transform_discovery_message", "maltegoV3TransformDiscoveryMessage"),
        (V3StatusResponse, "v2_transform_count", "v2TransformCount"),
        (V3StatusResponse, "v3_transform_count", "v3TransformCount"),
        # Already-camelCase field names: title() lowercases the inner capitals.
        (TransformRunRequest, "transformSettings", "transformsettings"),
        (TransformRunRequest, "transformRunExecutionContext", "transformrunexecutioncontext"),
    ],
)
def test_protocol_field_alias(model, field, alias):
    info = model.model_fields[field]
    assert (info.alias, info.validation_alias, info.serialization_alias) == (alias, alias, alias)


_STATUS = {
    "startup_time": 1.5,
    "v2_transform_count": 2,
    "v3_transform_count": 3,
    "entity_count": 4,
    "entity_category_count": 5,
    "transform_set_count": 6,
    "icon_count": 7,
    "machine_count": 8,
}


def test_status_response_serializes_by_alias():
    assert V3StatusResponse(**_STATUS).model_dump(by_alias=True) == {
        "startupTime": 1.5,
        "v2TransformCount": 2,
        "v3TransformCount": 3,
        "entityCount": 4,
        "entityCategoryCount": 5,
        "transformSetCount": 6,
        "iconCount": 7,
        "machineCount": 8,
    }


def test_run_request_accepts_client_camel_case_by_field_name():
    """Clients send ``transformSettings``; it only validates because input by field name is allowed."""
    request = TransformRunRequest.model_validate({
        "input": {
            "metadata": {"entitiesTypesStat": {}, "entitiesTotalCount": 0},
            "graph": {"entities": [], "links": []},
        },
        "transformSettings": [{"name": "api.key", "value": "x"}],
        "transformRunExecutionContext": {"graphId": "g", "runSource": "DIRECT", "sourceName": None},
    })
    assert request.transformSettings == [TransformSetting(name="api.key", value="x")]
    assert request.transformRunExecutionContext is not None
    assert request.transformRunExecutionContext.graph_id == "g"


def test_protocol_model_validates_from_attributes():
    status = V3StatusResponse.model_validate(SimpleNamespace(**_STATUS))
    assert status.model_dump() == _STATUS
